### ISSUE TITLE
建议推出协程版

### ISSUE THREAD

**Issue by Yurunsoft** [hprose/hprose-swoole#11]
现在用的异步已经被swoole新版本砍掉，作为独立扩展了。使用swoole推荐用协程，是否实现一下协程版本。其实主要是websocket、http版本需要swoole的。socket版本可以使用swoole一键协程化来做支持。

**Comment by andot** [comment]
正有此打算，扩展昨日已更新，端午节看看能不能把 php 的 hprose 3.0 完成。序列化部分就不重写了，直接用扩展版本了，连 php 版本也不写了。
