### ISSUE TITLE
composer.json是否有误？

### ISSUE THREAD

**Issue by geekchu** [hprose/hprose-swoole#2]
"require": {
        "php": ">=5.3.0",
        "hprose/hprose": ">=2.0.9",
        "ext-swoole": ">=1.8.8"
    },

应为 "hprose/hprose-php":">=2.0.9"

**Comment by andot** [comment]
并没有错，hprose/hprose-php 这个包不是官方的，是一个 hprose 用户在很久之前 fork 了一份发布到 packagist 上面的一个包，这个版本是很旧的。

hprose/hprose 这个包才是对应的官方的 hprose/hprose-php 项目的。
