### ISSUE TITLE
TCP 方式请求，客户端不主动调用close的情况下报warning

### ISSUE THREAD

**Issue by zengbo** [hprose/hprose-swoole#7]
用的是README里面的代码，执行 tcp_cliet.php 报warning：

Warning: swoole_timer_clear(): timer#11 is not found. in src/Hprose/Swoole/Socket/Transporter.php on line 42

PHP 版本： 7.2.2
Swoole 版本：2.1.0

**Comment by andot** [comment]
我修改了一下，你试试现在可以了吗？

**Comment by zengbo** [comment]
可以了～

**Comment by andot** [comment]
非常感谢~
